/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parks.telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

import br.com.parks.service.TrapGroupServiceImpl;
import br.com.parks.service.TrapServiceImpl;
import br.com.parks.trapgroup.TrapGroup;

/**
 * 
 * @author User
 */
@SuppressWarnings("serial")
public class ManagerGroupPanel extends javax.swing.JFrame {

	TrapGroupServiceImpl groupService = new TrapGroupServiceImpl();
	TrapServiceImpl trapService = new TrapServiceImpl();
	private DefaultListModel groupListModel;
	private TrapSenderPanel trapSenderPanel;
	private TrapPanel trapPanel;

	/**
	 * Creates new form ManagerGroupPanel
	 */
	public ManagerGroupPanel(TrapSenderPanel trapSenderPanel,
			TrapPanel trapPanel) {
		initComponents();
		init();
		this.trapSenderPanel = trapSenderPanel;
		this.trapPanel = trapPanel;
	}

	public ManagerGroupPanel(TrapSenderPanel trapSenderPanel) {
		initComponents();
		init();
		this.trapSenderPanel = trapSenderPanel;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanelBorda = new javax.swing.JPanel();
		jPanelForm = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListGroup = new javax.swing.JList();
		jPanelBotoes = new javax.swing.JPanel();
		jButtonAddGroup = new javax.swing.JButton(new ImageIcon(
				"images/add.png"));
		jButtonRemoveGroup = new javax.swing.JButton(new ImageIcon(
				"images/delete.png"));
		jButtonEditGroup = new javax.swing.JButton(new ImageIcon(
				"images/edit.png"));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Manager Group Trap");

		jPanelBorda.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Group Manager"));
		jPanelBorda.setLayout(new java.awt.BorderLayout());

		jPanelForm.setLayout(new java.awt.GridBagLayout());

		jListGroup.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jListGroupMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jListGroup);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 30;
		gridBagConstraints.ipady = 25;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
		jPanelForm.add(jScrollPane1, gridBagConstraints);

		jPanelBotoes.setLayout(new java.awt.GridBagLayout());

		jButtonAddGroup.setBorder(null);
		jButtonAddGroup.setBorderPainted(false);
		jButtonAddGroup.setContentAreaFilled(false);
		jButtonAddGroup.setFocusPainted(false);
		jButtonAddGroup.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAddGroupActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
		jPanelBotoes.add(jButtonAddGroup, gridBagConstraints);

		jButtonRemoveGroup.setBorder(null);
		jButtonRemoveGroup.setBorderPainted(false);
		jButtonRemoveGroup.setContentAreaFilled(false);
		jButtonRemoveGroup.setFocusPainted(false);
		jButtonRemoveGroup
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonRemoveGroupActionPerformed(evt);
					}
				});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
		jPanelBotoes.add(jButtonRemoveGroup, gridBagConstraints);

		jButtonEditGroup.setBorder(null);
		jButtonEditGroup.setBorderPainted(false);
		jButtonEditGroup.setContentAreaFilled(false);
		jButtonEditGroup.setFocusPainted(false);
		jButtonEditGroup.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonEditGroupActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
		jPanelBotoes.add(jButtonEditGroup, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
		jPanelForm.add(jPanelBotoes, gridBagConstraints);

		jPanelBorda.add(jPanelForm, java.awt.BorderLayout.CENTER);

		getContentPane().add(jPanelBorda, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void init() {
		// set componente no meio da tela
		this.setLocationRelativeTo(null);

		// list
		setGroupListModel(new DefaultListModel());
		jListGroup.setModel(getGroupListModel());

		// adiciona grupos na lista
		addGroups();
	}

	private void addGroups() {
		for (TrapGroup group : groupService.getGroups()) {
			getGroupListModel().addElement(group);
		}
	}

	private void jButtonAddGroupActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAddGroupActionPerformed
		addGroupPanel();
	}// GEN-LAST:event_jButtonAddGroupActionPerformed

	private void addGroupPanel() {
		new TrapGroupPanel(getGroupListModel(), this.trapSenderPanel,
				this.trapPanel).setVisible(true);
	}

	private void jButtonRemoveGroupActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRemoveGroupActionPerformed
		removeGroup();
	}// GEN-LAST:event_jButtonRemoveGroupActionPerformed

	private void removeGroup() {
		if (jListGroup.getSelectedValue() != null) {
			String[] optionMessages = { "Yes", "No" };
			TrapGroup group = (TrapGroup) jListGroup.getSelectedValue();

			String msg;
			if (trapService.getTrapsByGroup(group.getId()).size() > 0) {
				msg = "This group ("
						+ jListGroup.getSelectedValue()
						+ ") contains "
						+ trapService.getTrapsByGroup(group.getId()).size()
						+ " traps registered. \nDo you want remove this group and all traps?";
			} else {
				msg = "Do you want remove this group (" + group.toString()
						+ ") ?";
			}

			int removeYes = JOptionPane.showOptionDialog(null, msg,
					"Attention", JOptionPane.YES_OPTION,
					JOptionPane.QUESTION_MESSAGE, null, optionMessages, null);
			if (removeYes == JOptionPane.YES_OPTION) {
				trapService.removeTrapsByGroupId(group.getId());
				groupService.removeGroup((TrapGroup) jListGroup
						.getSelectedValue());
				getGroupListModel()
						.removeElement(jListGroup.getSelectedValue());
				trapSenderPanel.updateGroups();
				JOptionPane.showMessageDialog(null, "Group removed", "Success",
						JOptionPane.INFORMATION_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(null, "You need select an item.",
					"Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void jButtonEditGroupActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEditGroupActionPerformed
		editGroupPanel();
	}// GEN-LAST:event_jButtonEditGroupActionPerformed

	private void editGroupPanel() {
		if (jListGroup.getSelectedValue() != null) {
			new TrapGroupPanel(groupListModel, jListGroup.getSelectedIndex(),
					jListGroup.getSelectedValue(), this.trapSenderPanel,
					this.trapPanel).setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "You need select an item.",
					"Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	@SuppressWarnings("static-access")
	private void jListGroupMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jListGroupMouseClicked
		if (evt.getButton() == evt.BUTTON3) {
			showJListManagerMenu(evt);
		}

		if (evt.getClickCount() > 1) {
			editGroupPanel();
		}

	}// GEN-LAST:event_jListGroupMouseClicked

	private void showJListManagerMenu(java.awt.event.MouseEvent evt) {
		JPopupMenu popup = new JPopupMenu();
		JMenuItem item1 = new JMenuItem("Add group");
		item1.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				addGroupPanel();
			}
		});
		popup.add(item1);

		if (jListGroup.getSelectedValue() != null) {
			JMenuItem item2 = new JMenuItem("Edit group");
			item2.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					editGroupPanel();
				}
			});
			popup.add(item2);

			JMenuItem item3 = new JMenuItem("Remove group");
			item3.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					removeGroup();
				}
			});
			popup.add(item3);

		}

		popup.show(jListGroup, evt.getX(), evt.getY());
	}

	public DefaultListModel getGroupListModel() {
		return groupListModel;
	}

	public void setGroupListModel(DefaultListModel groupListModel) {
		this.groupListModel = groupListModel;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAddGroup;
	private javax.swing.JButton jButtonEditGroup;
	private javax.swing.JButton jButtonRemoveGroup;
	private javax.swing.JList jListGroup;
	private javax.swing.JPanel jPanelBorda;
	private javax.swing.JPanel jPanelBotoes;
	private javax.swing.JPanel jPanelForm;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
